import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Textbox from '../components/Textbox'

export default function Home() {
  return (
    <div className='text-prussianblue'>
      <Head>
        <title>Startseite Testzentrum</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='min-h-screen bg-ghostwhite '>
      <Header test="hallo">Corona Testzentrum</Header>
      <Textbox title="Überschrift 1" content="Inhalt 1"></Textbox>
      </main>

      <footer>
        
      </footer>
    </div>
  )
}
